########################################################################
#                                                                      #
# This file is part of libindi.                                        #
#                                                                      #
# libindi is free software: you can redistribute it and/or modify it   #
# under the terms of the GNU General Public License as published by    #
# the Free Software Foundation, either version 3 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# libindi is distributed in the hope that it will be useful, but       #
# WITHOUT ANY WARRANTY; without even the implied warranty of           #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                 #
# See the GNU General Public License for more details.                 #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with libindi.  If not, see <http://www.gnu.org/licenses/>.     #
#                                                                      #
########################################################################

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{indi}: {mxx hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBINDI_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBINDI_SHARED_BUILD

# Export options.
#
lib{indi}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{indi}: cxx.export.poptions += -DLIBINDI_STATIC
libs{indi}: cxx.export.poptions += -DLIBINDI_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{indi}: bin.lib.version = "-$version.project_id"
else
  lib{indi}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libindi/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{mxx hxx ixx txx}{*}:
{
  install         = include/libindi/
  install.subdirs = true
}
